businessProject/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views			

app_name = 'accounts'
urlpatterns = [
    path('login/',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'
    ),
    path('logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

businessProject/businessProject/urls.py
from django.contrib import admin
from django.urls import path, include
from request.views import DashboardView, RouteView

urlpatterns = [
    path('', RouteView.as_view(), name='route'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('route/', RouteView.as_view(), name='route'),
    path('request/', include('request.urls')),
    path('accounts/', include('accounts.urls')),
    path('settings/', include('settings.urls')),
    path('notification/', include('notification.urls')),
    path('message/', include('message.urls')),
    path("admin/", admin.site.urls),
]

businessProject/message/urls.py
from django.urls import path
from .views import MessageListView, MessageCreateView, MessageMarkReadView

app_name = 'message'
urlpatterns = [
    path('', MessageListView.as_view(), name='message_list'),
    path('create/', MessageCreateView.as_view(), name='message_create'),
    path('mark_as_read/<int:message_id>/', MessageMarkReadView.as_view(), name='mark_as_read'),
]

businessProject/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""
    
    EMPLOYEE_TYPES = [
        ('内定者', '内定者'),
        ('社員', '社員'),
        ('退職者', '退職者'),
        ('人事', '人事'),
    ]

    employee_type = models.CharField(
        max_length=20,
        choices=EMPLOYEE_TYPES,
        default='内定者',
        verbose_name='社員属性'
    )

    date_of_joining = models.DateField(
        null=True,
        blank=True,
        verbose_name='入社日'
    )

    is_first_login = models.BooleanField(
        default=True,
        verbose_name='初回ログイン'
    )

businessProject/accounts/forms.py
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm

class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

businessProject/accounts/views.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from .forms import MyPasswordResetForm, MySetPasswordForm


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""

    subject_template_name = 'accounts/password_reset_mail/subject.txt'
    email_template_name = 'accounts/password_reset_mail/message.txt'
    template_name = 'accounts/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""

    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""

    form_class = MySetPasswordForm
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""

    template_name = 'accounts/password_reset_complete.html'

businessProject/templates/accounts/login.html
{% extends "request/base.html" %}
{% load static %}
{% block title %}ログイン{% endblock %}
{% block content %}

{% block navbar %}{% endblock %}

<section class="section section-shaped section-lg min-vh-100">
    <div class="shape shape-style-1 bg-gradient-default">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div class="container pt-lg-7">
      <div class="row justify-content-center">
        <div class="col-lg-5">
          <div class="card bg-secondary shadow border-0">
            <div class="card-body px-lg-5 py-lg-5">
              <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
              {% if form.errors %}
                <p style="color: red">ユーザー名とパスワードが一致しません。</p>
              {% endif %}
              <form role="form" method="post">
                {% csrf_token %}
                <div class="form-group mb-3">
                  <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fa fa-id-card"></i></span>
                    </div>
                    <input class="form-control" placeholder="ユーザーID" type="text" name="username">
                  </div>
                </div>
                <div class="form-group focused">
                  <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                    </div>
                    <input class="form-control" placeholder="パスワード" type="password" name="password">
                  </div>
                </div>
                <input type="hidden" name="next" value="{% url 'dashboard' %}">
                <div class="text-center">
                  <button type="submit" class="btn btn-primary my-3">ログイン</button>
                </div>
                <!-- パスワードを忘れた場合のリンク -->
                <div class="text-center">
                  <a href="{% url 'accounts:password_reset' %}" class="text-light"><small>パスワードを忘れた場合</small></a>
                </div>

                <div class="text-center">
                  <a href="{% url 'route' %}" class="btn btn-outline-primary my-3">経路探索</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

businessProject/templates/accounts/password_reset_complete.html
{% extends "request/base.html" %}
{% load static %}
{% block title %}パスワード再設定{% endblock %}
{% block content %}

{% block navbar %}{% endblock %}

<section class="section section-shaped section-lg min-vh-100">
    <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div class="container pt-lg-7">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card bg-secondary shadow border-0">
                    <div class="card-body px-lg-5 py-lg-5">
                        <p>パスワード再設定を完了しました。</p>
                        <div class="text-center">
                            <a class="btn btn-primary btn-lg" href="{% url 'accounts:login' %}">ログイン</a>
                          </div>
                    </div>
                </div>
            </div>
        </div>
</section>
{% endblock %}

businessProject/templates/accounts/password_reset_confirm.html
{% extends "request/base.html" %}
{% load static %}
{% block title %}パスワード再設定{% endblock %}
{% block content %}

{% block navbar %}{% endblock %}

<section class="section section-shaped section-lg min-vh-100">
    <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div class="container pt-lg-7">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card bg-secondary shadow border-0">
                    <div class="card-body px-lg-5 py-lg-5">
                        <form action="" method="POST">
                            {{ form.non_field_errors }}
                            {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                                {{ field }}
                                {{ field.errors }}
                            </div>
                            {% endfor %}
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary btn-lg">送信</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
</section>
{% endblock %}

businessProject/templates/accounts/password_reset_done.html
{% extends "request/base.html" %}
{% load static %}
{% block title %}パスワード再設定{% endblock %}
{% block content %}

{% block navbar %}{% endblock %}

<section class="section section-shaped section-lg min-vh-100">
    <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div class="container pt-lg-7">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card bg-secondary shadow border-0">
                    <div class="card-body px-lg-5 py-lg-5">
                        <p>
                            パスワード再設定用のメールを送信しました。<br>
                            メールに記載されているリンクから再設定を行ってください。
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

businessProject/templates/accounts/password_reset_form.html
{% extends "request/base.html" %}
{% load static %}
{% block title %}パスワード再設定{% endblock %}
{% block content %}

{% block navbar %}{% endblock %}

<section class="section section-shaped section-lg min-vh-100">
    <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div class="container pt-lg-7">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card bg-secondary shadow border-0">
                    <div class="card-body px-lg-5 py-lg-5">
                        <form action="" method="POST">
                            {{ form.non_field_errors }}
                            {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                                {{ field }}
                                {{ field.errors }}
                            </div>
                            {% endfor %}
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary btn-lg">送信</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}